export const LOGIN = 'LOGIN';
export const SAVE_STATE_EXPENSES = 'SAVE_STATE_EXPENSES';
export const FETCH_API_THUNK_EXCHANGE_RATES = 'FETCH_API_THUNK_EXCHANGE_RATES';
export const FETCH_API_HAS_STARTED = 'FETCH_API_HAS_STARTED';
export const FETCH_API_HAS_FINISHED = 'FETCH_API_HAS_SFINISHED';
export const FETCH_API_HAS_ERROR = 'FETCH_API_HAS_SFINISHED';
