export const USER_INFO = 'USER_INFO';
export const GET_CURRENTEXCHANGE_SUCCESS = 'GET_CURRENTEXCHANGE_SUCCESS';
export const GET_CURRENTEXCHANGE_FAIL = 'GET_CURRENTEXCHANGE_SUCCESS';
export const DELETE_ITEMS = 'DELETE_ITEMS';
export const UPDATE_ITEMS_MODE = 'UPDATE_ITEMS_MODE';
export const UPDATE_ITEMS = 'UPDATE_ITEMS';
