export const ADD_USER = 'ADD_USER';
export const GET_EXCHANGE_RATE = 'GET_EXCHANGE_RATE';
export const IS_FETCHING = 'IS_FETCHING';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const REFRESH_EXPENSES = 'REFRESH_EXPENSES';
