const REGISTER_USER = 'REGISTER_USER';
const LOADING_ACTION = 'LOADING_ACTION';
const LOADING_ACTION_SUCCESS = 'LOADING_ACTION_SUCCESS';
const LOADING_ACTION_FAIL = 'LOADING_ACTION_FAIL';
const API_URL = 'https://economia.awesomeapi.com.br/json/all';

export {
  REGISTER_USER,
  LOADING_ACTION,
  LOADING_ACTION_SUCCESS,
  LOADING_ACTION_FAIL,
  API_URL,
};
