const REGISTER_USER = 'REGISTER_USER';
const UPDATE_EXPENSES = 'UPDATE_EXPENSES';
const LOADING_ACTION = 'LOADING_ACTION';
const LOADING_ACTION_SUCCESS = 'LOADING_ACTION_SUCCESS';
const LOADING_ACTION_FAIL = 'LOADING_ACTION_FAIL';
const EDIT_EXPENSE = 'EDIT_EXPENSE';
const DELETE_EXPENSE = 'DELETE_EXPENSE';
const IS_EDITING = 'IS_EDITING';
const API_URL = 'https://economia.awesomeapi.com.br/json/all';

export {
  REGISTER_USER,
  UPDATE_EXPENSES,
  LOADING_ACTION,
  LOADING_ACTION_SUCCESS,
  LOADING_ACTION_FAIL,
  EDIT_EXPENSE,
  DELETE_EXPENSE,
  IS_EDITING,
  API_URL,
};
